# Generated by Django 4.2.4 on 2023-09-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_content_product_price_product_title'),
        ('products', '0002_product_user'),
    ]

    operations = [
    ]
