# Generated by Django 4.0.10 on 2023-09-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_20230918_1016'),
        ('products', '0003_product_public'),
    ]

    operations = [
    ]
